---
- name: Install nginx
  apt: pkg=nginx state=latest

- name: Create nginx main configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Create tomatocart nginx configuration
  template: src=tomatocart.conf dest=/etc/nginx/sites-available/tomatocart.conf

- name: Delete default nginx configuration
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Create link for nginx configuration
  file: src=/etc/nginx/sites-available/tomatocart.conf dest=/etc/nginx/sites-enabled/tomatocart.conf state=link
  notify: restart nginx
